// User
//Login
export const LOGIN = 'LOGIN'
export const RESET_PASSWORD = "RESET PASSWORD"
export const SET_USER_INFO = 'SET_USET_INFO'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'

//Register
export const CHECK_EMAIL_EXISTE = "CHECK EMAIL EXISTE"
export const GET_LIST_QUESTION_SYSTEM = "GET LIST QUESTION SYSTEM"
export const GET_ETHNIC_ANSWERS = "GET ETHNIC ANSWERS"
export const REGISTER_NEW_USER = "REGISTER NEW USER"

export const GET_COUNTRY = "GET COUNTRY"
export const GET_VILLE = "GET VILLE"
export const GET_CODE_POSTAL = "GET CODE POSTAL"

export const GET_TERMS_CONDTIONS = "GET TERMS CONDTIONS"
export const GET_TERMS_CONDTIONS_DATA_SENSITIVE = "GET TERMS CONDTIONS DATA SENSITIVE"

//Main Action
export const SET_DEVICE_TOKEN = "SET_DEVICE_TOKEN"
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_DETAIL_CATEGORY = "GET_DETAIL_CATEGORY"
export const SEND_NOTIFI = 'SEND_NOTIFI'
export const DELETE_TYPE = 'DELETE_TYPE'

//Notification 
export const GET_HISTORY = "GET_HISTORY"
export const GET_STATUS_USER = "GET_STATUS_USER"
export const GET_STATUS_USER_REDUX = 'GET_STATUS_USER_REDUX'
export const GET_COMPATIBILITY_FIND_USER = "GET_COMPATIBILITY_FIND_USER"
export const POST_ACCEPTER_COMPATIBILY = "POST_ACCEPTER_COMPATIBILY"
export const POST_REJECT_COMPATIBILY = "POST_REJECT_COMPATIBILY"
export const POST_DELETE_NOTIFICATION = 'POST_DELETE_NOTIFICATION'

//Home
export const GET_HOME_PERSONAL = 'GET_HOME_PERSONAL'
export const GET_HOME_POSITION = 'GET_HOME_POSITION'
export const GET_HOME_PLAN_TIME = 'GET_HOME_PLAN_TIME'
export const POST_SAVE_PLAN_TIME = 'POST_SAVE_PLAN_TIME'
export const GET_STATUS_HOME = 'GET_STATUS_HOME'
export const GET_STATUS_HOME_REDUCER = 'GET_STATUS_HOME_REDUCER'
export const POST_DELAY_DATING = 'POST_DELAY_DATING'
export const POST_REPLANTIME_DATING = 'POST_REPLANTIME_DATING'
export const POST_SEND_FEED_BACK = 'POST_SEND_FEED_BACK'
export const GET_LASTER_NOTIFICATION = 'GET_LASTER_NOTIFICATION'
export const GET_NOTIFI = 'GET_NOTIFI'
export const DELETE_NOTIFI = 'DELETE_NOTIFI'

//Setting
export const POST_DELETE_ACCOUNT = 'POST_DELETE_ACCOUNT'
export const POST_CHANGE_EMAIL_ACCOUNT = 'POST_CHANGE_EMAIL_ACCOUNT'
export const POST_CHANGE_PASS_ACCOUNT = 'POST_CHANGE_PASS_ACCOUNT'
export const POST_LOG_OUT = 'POST_LOG_OUT'

// persional
export const POST_USER_ANSWER = 'POST_USER_ANSWER'
export const PUT_RELISION = 'PUT_RELISION'
export const PUT_UPDATE_LOCATION = 'PUT_UPDATE_LOCATION'
export const POST_IMAGE = 'POST_IMAGE'
export const GET_IMAGE = 'GET_IMAGE'